### PR TITLE
Add support for GeometryCollections

### PR DESCRIPTION
**Pull request by mfogel**
Also pretty self-explanatory, but let me know if you have questions or would like to see any tweaks made. Cheers.

### CODE REVIEW

**Comment by gagan-bansal** [comment]
Thanks for pull request I'll go through it soon.

**Comment by gagan-bansal** [comment]
Does the order of geomtryies/features in GeometryCollection/FeatureCollection matter? Its not clear to me. There is a point in [Geojson RFC](https://tools.ietf.org/html/rfc7946#section-1.4) (last point) about order but I could not get fully.

I have put up [this question](https://gis.stackexchange.com/q/268702/12962) in forum, lets wait for the outcome.

Its good that you have written all possible test cases.

**Comment by mfogel** [comment]
Yeah, I wasn't sure if the collections should be treated as ordered or not. The PR treats them as ordered mainly because if it doesn't, then it could result in O(n^2) comparisons to compare two collections (at least in a naive implementation, there may be a smart way around that).

My take from that blurb in the RFC you linked to is that the collections being `standard ordered JSON arrays` would mean that order does indeed matter, though what meaning it has I don't know :)

**Comment by gagan-bansal** [comment]
Yes you are right its ordered, see [comments](https://gis.stackexchange.com/q/268702/12962). @ThingumaBob gave suitable reason also.

Thanks again.

**Pull request merged**
